name: "Conflict Merker Detector"
description: "Detect if any conflict markers remain in the diff of the Pull Request."

runs:
  using: "composite"
  steps:
    - name: Detect conflict markers
      shell: pwsh
      run: |
        Write-Output "Hello, World!"
